variable "project_name" {}
variable "ecs_tasks_execution_role_arn" {}
variable "repository_url" {}
variable "public_subnet_az1_id" {}
variable "public_subnet_az2_id" {}
variable "alb_security_group_id" {}
variable "alb_target_group_arn" {}
variable "log_group_name" {}
variable "log_group_arn" {}
variable "region" {}